catalog/urls.py
from django.urls import path
from . import views
from libraryproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    # path('book/(?P<pk>[0-9]+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksListView.as_view(), name='borrowed'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

# urlpatterns += [
#     path('booksearch/', views.BookSearchListView.as_view(), name='search_book')
# ]

urlpatterns += [
    path('book/<int:pk>/email/', views.emailview, name='email'),
]

urlpatterns += [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

urlpatterns += [
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
]

libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('improve/', include('improve.urls')),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date
# Create your models here.


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    image = models.ImageField(upload_to='books/', default='books/temp.jpg', null=True)
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book', null=True)
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book', null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):    # pragma: no cover
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    image = models.ImageField(upload_to="authors", default="authors/temp.jpg")
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class FavBooks(models.Model):
    fav_book = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f'{self.fav_book}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='images/', null=True)
    number = models.CharField(max_length=10, blank=True, null=True)
    fav_book = models.ManyToManyField(FavBooks, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username}'

catalog/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, Author, BookInstance, Profile, FavBooks
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import FormView, CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth import login, authenticate
from catalog.forms import RenewBookForm, EmailForm, SearchForm, ProfileForm
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.db.models import Q
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.contrib.auth.models import User
from functools import reduce
import operator
import json
# from django.http import HttpResponse
# from django.http import request
# Create your views here.


# def signup(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('index')
#     else:
#         form = UserCreationForm()
#     return render(request, 'signup.html', {'form', form})

class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


# try to make this a class-based view and include mixin for authentication
@login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_particular_books = Book.objects.filter(title__icontains='Assignment')

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_particular_books': num_particular_books,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2

    def get_queryset(self):
        object_list = super(BookListView, self).get_queryset()
        print("object_list = ", object_list)
        # print("image location = ", Book.image.url)
        text = self.request.GET.get('search')
        if text:
            # print("filtered = ", Book.objects.filter(title__icontains=text))
            object_list = object_list.filter(title__icontains=text)
            # print("text=", text)
            # print("Edited object list = ", object_list)

        return object_list


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 2

    def get_queryset(self):
        object_list = super(AuthorListView, self).get_queryset()
        print("object_list = ", object_list)
        text = self.request.GET.get('search')
        if text:
            # print("filtered = ", Author.objects.filter(Q(first_name__icontains=text) | Q(last_name__icontains=text)))
            object_list = object_list.filter(Q(first_name__icontains=text) | Q(last_name__icontains=text))
            # print("text=", text)
            # print("Edited object list = ", object_list)
        return object_list


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksListView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed.html'
    paginate_by = 10
    # permission_required = 'can_mark_returned'

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o')


# @permission_required('catalog.can_mark_returned')
@staff_member_required
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}

    def test_func(self):
        return self.request.user.is_superuser


class AuthorUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

    def test_func(self):
        return self.request.user.is_superuser


class AuthorDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

    def test_func(self):
        return self.request.user.is_superuser


class BookCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Book
    fields = '__all__'
    # initial = {'date_of_death': '05/01/2018'}

    def test_func(self):
        return self.request.user.is_superuser


class BookUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre']

    def test_func(self):
        return self.request.user.is_superuser


class BookDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')

    def test_func(self):
        return self.request.user.is_superuser


@login_required
def emailview(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = EmailForm(request.POST)
        email_id = []
        if form.is_valid():
            email_id.append(form.cleaned_data['email_id'])
            email = EmailMessage(
                book.title,
                'Enjoy Reading',
                'vedansh.kedia.iitb@gmail.com',
                email_id,
            )
            email.attach_file('catalog/docs/'+book.title+'.pdf')
            email.send()
            return HttpResponseRedirect(reverse('my-borrowed'))
    else:
        form = EmailForm()
        return render(request, 'catalog/email_form.html', {'form': form})


# @login_required
# def profile_form(request):
#     if request.method == 'POST':
#         form = ProfileForm(request.POST)
#
#         # if form.is_valid():
#


class ProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'catalog/profile.html'
    form_class = ProfileForm
    success_url = '/catalog/'
    # fields = ['image', 'number', 'fav_book',]

    # user_instance = Profile.objects.filter(user=req)

    # def get(self, request, *args, **kwargs):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all()
        return context

    # def get(self, request, *args, **kwargs):
    #     if Profile.objects.get(user=request.user):

    def post(self, request, *args, **kwargs):
        # fav_book_list = []
        form = ProfileForm(request.POST, request.FILES)

        if form.is_valid():
            image = form.cleaned_data["image"]
            number = form.cleaned_data["number"]
            fav_book_list = request.POST.get("fav_book_list")
            fav_book_list = json.loads(fav_book_list)
            for fav_book in fav_book_list:
                print(fav_book)
                print("\n",FavBooks.objects.filter(fav_book=fav_book))
                print("\n",bool(FavBooks.objects.filter(fav_book=fav_book)))
                if bool(FavBooks.objects.filter(fav_book=fav_book)):
                    pass
                else:
                    FavBooks.objects.create(fav_book=fav_book)

            fav_book_object = FavBooks.objects.filter(fav_book__in=fav_book_list)

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-4">
            <img src="{{ book.image.url }}">
        </div>
        <div class="col-sm-8">
            <h1>Title: {{ book.title }}</h1>
            <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>

            <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            <p><strong>Language:</strong> {{ book.language }}</p>
            <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <p><strong>Summary:</strong> {{ book.summary }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h4>Copies</h4>
            {% for copy in book.bookinstance_set.all %}
                <hr>
                <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
                {% if copy.status != 'a' %}
                    <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
                {% endif %}
                <p><strong>Imprint:</strong> {{copy.imprint}}</p>
                <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <table class="table table-striped">
        {% for bookinst in bookinstance_list %}
            <tr class="{% if bookinst.is_overdue %}text-danger{% endif %} row">
                <td class="col-sm-5">
    {#              <a href="{% url 'book-detail' bookinst.book.pk %}">#}
                    {{bookinst.book.title}}
    {#              </a>#}
                </td>
                <td class="col-sm-5">
                    ({{ bookinst.due_back }})
                </td>
                <td class="col-sm-2">
                    {% if perms.catalog.can_mark_returned %}
                        {{ bookinst.borrower }}
                        <a href="{% url 'renew-book-librarian' bookinst.id %}">
                            Renew
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <table>

        {% for bookinst in bookinstance_list %}
            <tr class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <td>
                    <a href="{{ bookinst.book.get_absolute_url }}">{{bookinst.book.title}}</a>
                </td>
                <td>
                    ({{ bookinst.due_back }})
                </td>
                <td>
                    <a href="{% url 'email' bookinst.book.pk %}">email</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/profile.html
{% extends "base_generic.html" %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% load widget_tweaks %}
{#--------------------------------------Code---------------------------------------------#}

{% block content %}


{#    -----------------------------------Scripts------------------------------------------------#}


{#    ------------------------------display image and number field---------------------#}

<form method="post" id="profile_form" enctype="multipart/form-data" novalidate>
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}


    {#    ------------------------------display image and number field---------------------#}
{#    ----------------------------------------------------------------------------------------#}
    {#    ------------------------------display favourite books---------------------#}
    <div class="form-group">

        {#  -------------------------display list box-------#}
        <label for="list">Favourite Books:</label>



        <ul class="list-group" id = "list">
            {% for each in profile.fav_book.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span id="list_content">{{ each }}</span>
{#                    <span class="badge badge-primary badge-pill"><a href="#">-</a></span>#}
                </li>
            {% endfor %}
        </ul>
        {#  -------------------------display list box-------  #}


        {#  -------------------------display dropdown -------  #}
{#        <div class="dropdown show fav_book1 inline-group" style="display: block">#}
{#            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                Add new favourite book#}
{#            </a>#}
{##}
{#            <div class="dropdown-menu form-control" aria-labelledby="dropdownMenuLink">#}
{#                {% for each in books.all %}#}
{#                    <a class="dropdown-item" href="#" id="{{ each|escape }}" content="{{ each|escape }}" value="{{ each|escape }}">{{ each|force_escape }}</a>#}
{#                {% endfor %}#}
{#            </div>#}
{#            <button type="button" id="display_text_box" class="btn btn-light fav_book1">Add Custom</button>#}
{#        </div>#}







    <select class="dropdown show display_text_box inline-group">
        {% for each in books.all %}
            <option class="dropdown-item" value="{{ each|force_escape }}">{{ each|force_escape }}</option>
        {% endfor %}
    </select>
    <button type="button" id="display_text_box" class="btn btn-light display_text_box">Add Custom</button>



        {#  -------------------------display dropdown -------  #}


        <div class="text_input display_dropdown">
            <input type="text" id="input_text_box" class="form-control fav_book2">
            <button type="button" class="btn btn-dark" id="text_input_button">add</button>
            <button type="button" id="display_list" class="btn btn-light fav_book2">Select from List</button>
        </div>
    </div>

{#    ------------------------------ display favourite books ---------------------#}
<input  type="hidden" id="fav_book_list" value="" name="fav_book_list">

</form>


    <div class="form-group">
        <button id="submit_button" class="btn btn-primary">Submit</button>
    </div>

{#--------------------------------------------------------------------------------------------#}
{#                                     Scripts                                                    #}
{#    -----------------------------------------------------------------------------------------#}

    <script>
        $(document).ready(function(){
            $(".text_input").hide();
            $(".dropdown").show();

            var optionTexts = [];
            $(".form-group ul li span#list_content").each(function() { optionTexts.push($(this).text()) });

            {#-----------------Toggle between text box and dropdown--------------------#}

            $("#display_text_box").click(function(){
                console.log("input field be shown");
                $(".display_text_box").hide();
                $(".text_input").show();
            });
            $("button.display_dropdown").click(function(){
                console.log("input field be shown");
                $(".dropdown").show();
                $(".text_input").hide();
            });

            {#-------------------Dropdown Element to list box and---- PUSH TO ARRAY-------------------------------#}

            $(".dropdown").click(function(){

                var item= $(this).find("option:selected").val();

                {#console.log(item);#}
                $("ul.list-group").append(`<li class="list-group-item d-flex justify-content-between align-items-center">`
                    + `<span>`
                    + item
                    + `</span>`
                    + `</li>`);
                optionTexts.push(item);

            });


            $("#id_number").blur(function(){
                var a = $("#id_number").val();
                var filter = /[1-9]{1}[0-9]{9}/;
                if (filter.test(a)) {
                    {#alert("correct", a);#}
                }
                else {
                    alert("incorrect", a);
                }
            });

            $("#id_number").focus(function () {

                console.log("check image uploaded");

                if($("#id_image").val() == false) {
                    alert('upload an image');
                    $("#id_image").focus();
                }
            });



            $('INPUT[type="file"]').change(function(){
                var ext = $('#id_image').val().split('.').pop().toLowerCase();
                if($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
                    alert('invalid extension!');
                    $("#id_image").val("");
                }
            });






            {#------------------Text box Element to LIST box and ARRAY----------------------------#}

            $("#text_input_button").click(function(){

                var item= $("#input_text_box").val();

                if (item.replace(/^\s+|\s+$/g, "").length != 0){
                    console.log("text box input");
                console.log(item);
                $("ul.list-group").append(`<li class="list-group-item d-flex justify-content-between align-items-center">`
                    + `<span>`
                    + item
                    + `</span>`
                    + `</li>`);
                optionTexts.push(item);

                $("#input_text_box").val("");
                }
                else {
                    alert("No input found");
                }
            });




            $(".list-group li").click(function() {
                {#alert(this.id); // id of clicked li by directly accessing DOMElement property#}
                {#alert($(this).attr('id')); // jQuery's .attr() method, same but more verbose#}
                {#alert($(this).html()); // gets innerHTML of clicked li#}
                {#alert($(this).text()); // gets text contents of clicked li#}
                var removeItem = $(this).contents("span").text();
                if(!$(this).hasClass("selected")) {
                    $(this).addClass("selected");
                    {#optionTexts.splice( $.inArray(removeItem, optionTexts), 1 );#}
{#                    --#}
                    {#alert($(this).text());#}
                    {#optionTexts = jQuery.grep(optionTexts, function(value) {#}
                    {#  return value != $(this).text();#}
                    {# });#}
{#                    =-------#}

                    var result = optionTexts.filter(function(elem){
                       return elem != removeItem;
                    });
                    optionTexts = result;
                    console.log("remove item = ", removeItem);
                    console.log("result=",result);
                    console.log("optionText=",optionTexts);
                }
                else {
                    $(this).removeClass("selected");
                    optionTexts.push(removeItem);
                    console.log("remove item = ", removeItem);
                    {#console.log("result=",result);#}
                    console.log("optionText=",optionTexts);
                }

            });



            $("#remove_fav_book").click(function(){

                var item= $(this).find("a:visited")(".form-group.list-group.list-group-item#list_content").val();

                console.log("deleted item");

                console.log(item);

                optionTexts.pop(item);
             });


{#            --------------Submit Button to populate the array to Input and Submit------------------------------------------#}


            $("#submit_button").click(function(){
                console.log(optionTexts);
                var myJSON = JSON.stringify(optionTexts);
                {#document.getElementById("demo").innerHTML = myJSON;#}
                console.log(myJSON);
                $("#fav_book_list").val(myJSON);
                {#$(".form-group ul li span#list_content").each(function() { optionTexts.push($(this).text()) });#}
                $("#profile_form").submit()
            });



        });
    </script>
<div id="demo"></div>

{% endblock %}

{#---------------------------Decent Code-----------------------------------------------------#}

{#{% block content %}#}
{#  <form action="" method="post">#}
{#    {% csrf_token %}#}
{#    <table>#}
{#    {{ form.as_table }}#}
{#    </table>#}
{#    <input type="submit" value="Submit">#}
{#  </form>#}
{#{% endblock %}#}